# Generated by Django 5.2 on 2025-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
