# Generated by Django 5.2 on 2025-04-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gps_coordinate', models.CharField(max_length=255)),
                ('is_headquater', models.BooleanField(default=False)),
                ('is_other', models.BooleanField(default=False)),
            ],
        ),
    ]
