# Generated by Django 5.2 on 2025-05-02 04:09

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('parent', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='parent', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.category')),
            ],
        ),
    ]
