# Generated by Django 5.2 on 2025-04-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='children',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
    ]
