# Generated by Django 5.2 on 2025-05-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='sub_category',
        ),
    ]
