# Generated by Django 5.2 on 2025-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_delete_appointmets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
