# Generated by Django 5.2 on 2025-04-27 11:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointments_gender_and_more'),
        ('categories', '0003_rename_children_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select_category', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
