# Generated by Django 5.2 on 2025-04-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointments_category_and_more'),
        ('categories', '0003_rename_children_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select_sub_category', to='categories.category'),
        ),
    ]
