# Generated by Django 5.2 on 2025-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointments_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='payment_option',
            field=models.CharField(choices=[('ONLINE PAYMENT', 'online payment'), ('PAYMENT AT CLINIC', 'payment at clinic')], max_length=100),
        ),
    ]
